
version: 2
sources:
   - name: raw
     database: speedy-index-443511-i2
     schema: data_for_dbt
     tables:
       - name: raw_gz_sales
         description: "Sales data from Greenweez"
         alias: sales
       - name: raw_gz_product
         description: "Product details from Greenweez"
         alias: product
       - name: raw_gz_ship
         description: "Shipping data from Greenweez"
         alias: ship
models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
