version: 2

sources:
  - name: raw  
    schema: gz_raw_data
    description: "This is the raw data from Greenweez" 
    tables:
      - name: sales 
        identifier: raw_gz_sales 
        description: "This table contains the raw sales data from Greenweez"
      - name: product 
        identifier: raw_gz_product
        description: "Product details from Greenweez"
        
      - name: ship 
        identifier: raw_gz_ship
        description: "Shipping data from Greenweez"
        

models:
  - name: my_first_dbt_model 
    description: "A starter dbt model" 
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
