version: 2

sources:
  - name: raw # Alias for the dataset (name changed from 'gz_raw_data')
    schema: data_for_dbt # Actual schema in BigQuery
    description: "This is the raw data from Greenweez" # Added description for the source
    tables:
      - name: sales # Table name (you will change this if your raw table name is different)
        identifier: raw_gz_sales # Alias for the table
        description: "This table contains the raw sales data from Greenweez" # Description for the raw_gz_sales table
      - name: product # The raw product table in BigQuery
        identifier: raw_gz_product
        description: "Product details from Greenweez"
        
      - name: ship # The raw ship table in BigQuery
        identifier: raw_gz_ship
        description: "Shipping data from Greenweez"
        

models:
  - name: my_first_dbt_model # Name of your DBT model (can change as needed)
    description: "A starter dbt model" # Description of the model
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
